### ISSUE TITLE
Compilation error with boost 1.66.0

### ISSUE THREAD

**Issue by smichaku** [straks/straks#15]
Trying to build straks with boost 1.66.0 yields the following compilation error (works well with boost 1.65):

`
In file included from /usr/include/boost/multi_index/ordered_index.hpp:17:0,
                 from txmempool.h:27,
                 from miner.h:12,
                 from miner.cpp:8:
/usr/include/boost/multi_index/detail/ord_index_impl.hpp: In instantiation of ‘bool boost::multi_index::detail::ordered_index_impl<KeyFromValue, Compare, SuperMeta, TagList, Category, AugmentPolicy>::in_place(boost::multi_index::detail::ordered_index_impl<KeyFromValue, Compare, SuperMeta, TagList, Category, AugmentPolicy>::value_param_type, boost::multi_index::detail::ordered_index_impl<KeyFromValue, Compare, SuperMeta, TagList, Category, AugmentPolicy>::node_type*, boost::multi_index::detail::ordered_non_unique_tag) const [with KeyFromValue = boost::multi_index::identity<CTxMemPoolModifiedEntry>; Compare = CompareModifiedEntry; SuperMeta = boost::multi_index::detail::nth_layer<2, CTxMemPoolModifiedEntry, boost::multi_index::indexed_by<boost::multi_index::ordered_unique<modifiedentry_iter, CompareCTxMemPoolIter>, boost::multi_index::ordered_non_unique<boost::multi_index::tag<ancestor_score>, boost::multi_index::identity<CTxMemPoolModifiedEntry>, CompareModifiedEntry> >, std::allocator<CTxMemPoolModifiedEntry> >; TagList = boost::mpl::v_item<ancestor_score, boost::mpl::vector0<mpl_::na>, 0>; Category = boost::multi_index::detail::ordered_non_unique_tag; AugmentPolicy = boost::multi_index::detail::null_augment_policy; boost::multi_index::detail::ordered_index_impl<KeyFromValue, Compare, SuperMeta, TagList, Category, AugmentPolicy>::value_param_type = const CTxMemPoolModifiedEntry&; boost::multi_index::detail::ordered_index_impl<KeyFromValue, Compare, SuperMeta, TagList, Category, AugmentPolicy>::node_type = boost::multi_index::detail::ordered_index_node<boost::multi_index::detail::null_augment_policy, boost::multi_index::detail::index_node_base<CTxMemPoolModifiedEntry, std::allocator<CTxMemPoolModifiedEntry> > >; typename SuperMeta::type::node_type = boost::multi_index::detail::index_node_base<CTxMemPoolModifiedEntry, std::allocator<CTxMemPoolModifiedEntry> >]’:
/usr/include/boost/multi_index/detail/ord_index_impl.hpp:825:17:   required from ‘bool boost::multi_index::detail::ordered_index_impl<KeyFromValue, Compare, SuperMeta, TagList, Category, AugmentPolicy>::modify_(boost::multi_index::detail::ordered_index_impl<KeyFromValue, Compare, SuperMeta, TagList, Category, AugmentPolicy>::node_type*) [with KeyFromValue = boost::multi_index::identity<CTxMemPoolModifiedEntry>; Compare = CompareModifiedEntry; SuperMeta = boost::multi_index::detail::nth_layer<2, CTxMemPoolModifiedEntry, boost::multi_index::indexed_by<boost::multi_index::ordered_unique<modifiedentry_iter, CompareCTxMemPoolIter>, boost::multi_index::ordered_non_unique<boost::multi_index::tag<ancestor_score>, boost::multi_index::identity<CTxMemPoolModifiedEntry>, CompareModifiedEntry> >, std::allocator<CTxMemPoolModifiedEntry> >; TagList = boost::mpl::v_item<ancestor_score, boost::mpl::vector0<mpl_::na>, 0>; Category = boost::multi_index::detail::ordered_non_unique_tag; AugmentPolicy = boost::multi_index::detail::null_augment_policy; boost::multi_index::detail::ordered_index_impl<KeyFromValue, Compare, SuperMeta, TagList, Category, AugmentPolicy>::node_type = boost::multi_index::detail::ordered_index_node<boost::multi_index::detail::null_augment_policy, boost::multi_index::detail::index_node_base<CTxMemPoolModifiedEntry, std::allocator<CTxMemPoolModifiedEntry> > >; typename SuperMeta::type::node_type = boost::multi_index::detail::index_node_base<CTxMemPoolModifiedEntry, std::allocator<CTxMemPoolModifiedEntry> >]’
/usr/include/boost/multi_index/detail/ord_index_impl.hpp:860:25:   required from ‘bool boost::multi_index::detail::ordered_index_impl<KeyFromValue, Compare, SuperMeta, TagList, Category, AugmentPolicy>::modify_(boost::multi_index::detail::ordered_index_impl<KeyFromValue, Compare, SuperMeta, TagList, Category, AugmentPolicy>::node_type*) [with KeyFromValue = modifiedentry_iter; Compare = CompareCTxMemPoolIter; SuperMeta = boost::multi_index::detail::nth_layer<1, CTxMemPoolModifiedEntry, boost::multi_index::indexed_by<boost::multi_index::ordered_unique<modifiedentry_iter, CompareCTxMemPoolIter>, boost::multi_index::ordered_non_unique<boost::multi_index::tag<ancestor_score>, boost::multi_index::identity<CTxMemPoolModifiedEntry>, CompareModifiedEntry> >, std::allocator<CTxMemPoolModifiedEntry> >; TagList = boost::mpl::vector0<mpl_::na>; Category = boost::multi_index::detail::ordered_unique_tag; AugmentPolicy = boost::multi_index::detail::null_augment_policy; boost::multi_index::detail::ordered_index_impl<KeyFromValue, Compare, SuperMeta, TagList, Category, AugmentPolicy>::node_type = boost::multi_index::detail::ordered_index_node<boost::multi_index::detail::null_augment_policy, boost::multi_index::detail::ordered_index_node<boost::multi_index::detail::null_augment_policy, boost::multi_index::detail::index_node_base<CTxMemPoolModifiedEntry, std::allocator<CTxMemPoolModifiedEntry> > > >; typename SuperMeta::type::node_type = boost::multi_index::detail::ordered_index_node<boost::multi_index::detail::null_augment_policy, boost::multi_index::detail::index_node_base<CTxMemPoolModifiedEntry, std::allocator<CTxMemPoolModifiedEntry> > >]’
/usr/include/boost/multi_index_container.hpp:823:25:   required from ‘bool boost::multi_index::multi_index_container<Value, IndexSpecifierList, Allocator>::modify_(Modifier&, boost::multi_index::multi_index_container<Value, IndexSpecifierList, Allocator>::node_type*) [with Modifier = update_for_parent_inclusion; Value = CTxMemPoolModifiedEntry; IndexSpecifierList = boost::multi_index::indexed_by<boost::multi_index::ordered_unique<modifiedentry_iter, CompareCTxMemPoolIter>, boost::multi_index::ordered_non_unique<boost::multi_index::tag<ancestor_score>, boost::multi_index::identity<CTxMemPoolModifiedEntry>, CompareModifiedEntry> >; Allocator = std::allocator<CTxMemPoolModifiedEntry>; boost::multi_index::multi_index_container<Value, IndexSpecifierList, Allocator>::node_type = boost::multi_index::detail::ordered_index_node<boost::multi_index::detail::null_augment_policy, boost::multi_index::detail::ordered_index_node<boost::multi_index::detail::null_augment_policy, boost::multi_index::detail::index_node_base<CTxMemPoolModifiedEntry, std::allocator<CTxMemPoolModifiedEntry> > > >]’
/usr/include/boost/multi_index/detail/index_base.hpp:278:34:   required from ‘bool boost::multi_index::detail::index_base<Value, IndexSpecifierList, Allocator>::final_modify_(Modifier&, boost::multi_index::detail::index_base<Value, IndexSpecifierList, Allocator>::final_node_type*) [with Modifier = update_for_parent_inclusion; Value = CTxMemPoolModifiedEntry; IndexSpecifierList = boost::multi_index::indexed_by<boost::multi_index::ordered_unique<modifiedentry_iter, CompareCTxMemPoolIter>, boost::multi_index::ordered_non_unique<boost::multi_index::tag<ancestor_score>, boost::multi_index::identity<CTxMemPoolModifiedEntry>, CompareModifiedEntry> >; Allocator = std::allocator<CTxMemPoolModifiedEntry>; boost::multi_index::detail::index_base<Value, IndexSpecifierList, Allocator>::final_node_type = boost::multi_index::detail::ordered_index_node<boost::multi_index::detail::null_augment_policy, boost::multi_index::detail::ordered_index_node<boost::multi_index::detail::null_augment_policy, boost::multi_index::detail::index_node_base<CTxMemPoolModifiedEntry, std::allocator<CTxMemPoolModifiedEntry> > > >]’
/usr/include/boost/multi_index/detail/ord_index_impl.hpp:419:61:   required from ‘bool boost::multi_index::detail::ordered_index_impl<KeyFromValue, Compare, SuperMeta, TagList, Category, AugmentPolicy>::modify(boost::multi_index::detail::ordered_index_impl<KeyFromValue, Compare, SuperMeta, TagList, Category, AugmentPolicy>::iterator, Modifier) [with Modifier = update_for_parent_inclusion; KeyFromValue = modifiedentry_iter; Compare = CompareCTxMemPoolIter; SuperMeta = boost::multi_index::detail::nth_layer<1, CTxMemPoolModifiedEntry, boost::multi_index::indexed_by<boost::multi_index::ordered_unique<modifiedentry_iter, CompareCTxMemPoolIter>, boost::multi_index::ordered_non_unique<boost::multi_index::tag<ancestor_score>, boost::multi_index::identity<CTxMemPoolModifiedEntry>, CompareModifiedEntry> >, std::allocator<CTxMemPoolModifiedEntry> >; TagList = boost::mpl::vector0<mpl_::na>; Category = boost::multi_index::detail::ordered_unique_tag; AugmentPolicy = boost::multi_index::detail::null_augment_policy; boost::multi_index::detail::ordered_index_impl<KeyFromValue, Compare, SuperMeta, TagList, Category, AugmentPolicy>::iterator = boost::multi_index::detail::bidir_node_iterator<boost::multi_index::detail::ordered_index_node<boost::multi_index::detail::null_augment_policy, boost::multi_index::detail::ordered_index_node<boost::multi_index::detail::null_augment_policy, boost::multi_index::detail::index_node_base<CTxMemPoolModifiedEntry, std::allocator<CTxMemPoolModifiedEntry> > > > >; typename SuperMeta::type::node_type = boost::multi_index::detail::ordered_index_node<boost::multi_index::detail::null_augment_policy, boost::multi_index::detail::index_node_base<CTxMemPoolModifiedEntry, std::allocator<CTxMemPoolModifiedEntry> > >]’
miner.cpp:440:74:   required from here
/usr/include/boost/multi_index/detail/ord_index_impl.hpp:1181:7: error: no match for call to ‘(const key_compare {aka const CompareModifiedEntry}) (const CTxMemPoolModifiedEntry&, CTxMemPoolModifiedEntry&)’
       if(comp_(key(v),key(y->value())))return false;
       ^~
In file included from miner.cpp:8:0:
miner.h:84:10: note: candidate: bool CompareModifiedEntry::operator()(const CTxMemPoolModifiedEntry&, const CTxMemPoolModifiedEntry&) <near match>
     bool operator()(const CTxMemPoolModifiedEntry &a, const CTxMemPoolModifiedEntry &b)
          ^~~~~~~~
miner.h:84:10: note:   passing ‘const key_compare* {aka const CompareModifiedEntry*}’ as ‘this’ argument discards qualifiers
In file included from /usr/include/boost/multi_index/ordered_index.hpp:17:0,
                 from txmempool.h:27,
                 from miner.h:12,
                 from miner.cpp:8:
/usr/include/boost/multi_index/detail/ord_index_impl.hpp:1186:25: error: no match for call to ‘(const key_compare {aka const CompareModifiedEntry}) (CTxMemPoolModifiedEntry&, const CTxMemPoolModifiedEntry&)’
     return y==header()||!comp_(key(y->value()),key(v));
In file included from miner.cpp:8:0:
miner.h:84:10: note: candidate: bool CompareModifiedEntry::operator()(const CTxMemPoolModifiedEntry&, const CTxMemPoolModifiedEntry&) <near match>
     bool operator()(const CTxMemPoolModifiedEntry &a, const CTxMemPoolModifiedEntry &b)
          ^~~~~~~~
miner.h:84:10: note:   passing ‘const key_compare* {aka const CompareModifiedEntry*}’ as ‘this’ argument discards qualifiers
In file included from chain.h:14:0,
                 from miner.cpp:11:
`
